# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               David Won
tagline:             'A 2017 CS Graduate'
description:         ''
url:                 http://davidwon7.github.io
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]
paginate_path:       "page:num"

# About/contact
author:
  name:              David Won
  url:               https://twitter.com/mdo
  email:             davidwon7@gmail.com

# Custom vars
version:             1.0.0
